version: "3.8"

services:
  app:
    image: pls:test # TODO: change to artstay:latest
    container_name: pls
    ports:
      - "8000:8000"
    environment:
      ENV: PRODUCTION
      PORT: 8000
      DATABASE_URL: postgresql://zlaam:hellozlaam@localhost:5432/primeLogicFreelanceDB?schema=public
      SECRET_KEY: jsdfipasidfpakdfpkasdpofkaspdfkpsodifipsdfisp
      SMTP_HOST_EMAIL: mrzalaam@gmail.com
      SMTP_SECRET: yopv jfse vhxm nhal
      ADMIN_EMAIL1: zlaam.dev@gmail.com
      ADMIN_EMAIL2: athershahid37@gmail.com
      CLOUDINARY_API_SECRET: ctenCczZemAzgvzrbKu6YITBXMI
      CLOUDINARY_API_KEY: 476574998523984
      CLOUDINARY_NAME: denanem06
      CLOUDINARY_URL: cloudinary://476574998523984:ctenCczZemAzgvzrbKu6YITBXMI@denanem06

    volumes:
      - ./app:/usr/src/app
    restart: always
