name: Build and Deploy Pipeline
#Trigger will work only when the code is pushed to the branch.
on:
 push:
  branches:
    - main

jobs:
  build:
   runs-on: ubuntu-latest
   steps:
      # Checkout Repo
      - name: Checkout code 
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          
      # Installing pnpm package 
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Build project
        run: pnpm run build
        
  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      # Step 2: Set up SSH
      - name: Set up SSH key for deployment
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/deployerdev/.ssh.ssh/id_ed25519
          chmod 600 ~/deployerdev/.ssh.ssh/id_ed25519  # Set the correct permissions for the private key
      
      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no deployerdev@69.48.206.67 "cd /home/deployerdev/coding/projects/primelogic-solutions/backend_instance_1 && git pull origin main" 
         




     
