name: Build and Deploy Pipeline
#Trigger will work only when the code is pushed to the branch.
on:
 push:
  branches:
    - main

jobs:
  build:
   runs-on: ubuntu-latest
   steps:
      # Checkout Repo
      - name: Checkout code 
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
            cache: 'pnpm'
      # Installing pnpm package 
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Build project
        run: pnpm run build
     
