name: Build and Deploy Pipeline
#Trigger will work only when the code is push to main branch
on:
 push:
  branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code 
      uses: actions/checkout@v3
      
    - name: Install pnpm
        run: |
          npm install -g pnpm  # Install pnpm globally
          
    - name: Install Dependencies
      run: |
         pnpm build
       
    - name: Build Next.js application
      run: |
         pnpm run build
        
