name: Build and Deploy Pipeline
#Trigger will work only when the code is pushed to the branch.
on:
 push:
  branches:
    - main

jobs:
  build:
   runs-on: ubuntu-latest
   steps:
      # Checkout Repo
      - name: Checkout code 
        uses: actions/checkout@v3
      - name: update npm
        run: sudo apt update -y
      - name: Install npm
        run: sudo apt install -y nodejs npm
      # Installing pnpm package 
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install dependencies
        run: npm i
      - name: Build project
        run: pnpm run build
     
